name: Build keystone

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: x64

      - name: Install pkg-config
        shell: powershell
        run: |
          $pkgUrl = "https://github.com/lua-batteries/pkg-config/releases/download/v0.29.2/pkg-config-v0.29.2-x86_64-pc-windows-msvc.zip"
          $zipPath = "$env:TEMP\pkg-config.zip"
          Invoke-WebRequest -Uri $pkgUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "$env:TEMP\pkg-config"
          ls "$env:TEMP\pkg-config\bin"

      - name: Build keystone
        shell: cmd
        run: |
          REM run build script
          set PATH=%PATH%;%TEMP%\pkg-config\bin
          build_windows_binaries.bat

      - name: Delete existing tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete 0.9.2 --cleanup-tag --yes || echo "No release or tag found for 0.9.2"
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 0.9.2
          name: keystone_windows_builds
          body: |
            Release created by GitHub Actions

            - [x] Update CMake builds to successfully build with modern CMake
            - [x] Update C header includes to build with GCC 15
            - [x] Fix MSVC C2131 error in `RISCVAsmBackend.h` by replacing array_lengthof with `std::size` in static_assert for constant expression evaluation
            - [x] Added build_windows_binaries.bat to support building Windows binaries with two configurations `-DBUILD_SHARED_LIBS=ON` and `-DBUILD_SHARED_LIBS=OFF` 
          draft: false
          prerelease: false
          files: |
            build/kstool/kstool.exe
            build/llvm/lib/keystone.lib
            dll-build/llvm/bin/keystone.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}